//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaProMAX02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraProdProv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompraProdProv()
        {
            this.IdDetalleProvProds = new HashSet<IdDetalleProvProd>();
        }
    
        public int IdCompraProdProv { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdProveedores { get; set; }
    
        public virtual proveedore proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdDetalleProvProd> IdDetalleProvProds { get; set; }
    }
}
